# Generated by Django 5.2.8 on 2025-12-02 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socket_app', '0002_message_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='seen',
        ),
    ]
