# Generated by Django 5.2.8 on 2025-12-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socket_app', '0003_remove_message_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
